# .travis.yml -- Travis CI specification file.
# Copyright 2016-2017 the Tectonic Project
# Licensed under the MIT License.

language: rust
sudo: false

cache: cargo

os: osx
osx_image: xcode8.2

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - openssl aes-256-cbc -K $encrypted_bc40b17e21fa_key -iv $encrypted_bc40b17e21fa_iv
    -in dist/deploy_key.enc -out dist/deploy_key -d
  - brew update

install:
  - brew install graphite2
  - brew install harfbuzz --with-graphite2
  - brew install --force openssl

before_script:
  - |
    export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)/include &&
    export OPENSSL_LIB_DIR=$(brew --prefix openssl)/lib &&
    export DEP_OPENSSL_INCLUDE=$(brew --prefix openssl)/include &&
    export PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig

script:
  - |
    cargo build --verbose &&
    cargo test
