language = "C"
cpp_compat = true
style = "type"
include_guard = "BIBTEX_BINDINGS_H"
includes = ["tectonic_bridge_core.h"]

[export.rename]
"CoreBridgeState" = "ttbc_state_t"
"FileFormat" = "ttbc_file_format"
"InputHandle" = "ttbc_input_handle_t"

[enum]
prefix_with_name = true
