[book]
title = "The Tectonic Typesetting System"
authors = ["Tectonic Contributors"]
description = "A manual for the Tectonic typesetting system"
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/tectonic-typesetting/tectonic"
git-repository-icon = "fa-github"
